parameters:
    version: '0.1.0'

services:
    engine:
        class: \PoP\ConfigurationComponentModel\Engine\Engine
        public: true

    PoP\ConfigurationComponentModel\RouteModuleProcessors\:
        resource: '../src/RouteModuleProcessors/*'
        public: true
